### ISSUE TITLE
[checklist] minimal docs required for launch

### ISSUE THREAD

**Issue by sabman** [decision-labs/geobase-docs#2]
- [x] auth @Fergarram 
- [x] one blueprint @Fergarram 
- [x] docs on tile server @sabman 
- [x] getting started for developers @sabman 
- [x] getting started for GIS analysts @sabman
