### ISSUE TITLE
[checklist] Standardise guides & blueprints

### ISSUE THREAD

**Issue by sabman** [decision-labs/geobase-docs#3]
When we create a blueprint or a guide:

- [ ] I have a standard section for prerequisites
- [ ] I have a standard `.env.example`
- [ ] I have a standard migrations directory structure and instructions

We can create a template repo for this then always fork from it to create our guides and blueprints

related https://github.com/decision-labs/auth-geobase-svelte/issues/1
